#!/bin/bash
# Regenerate the application icons from the artwork in the repository root.
#
#   logo.svg          -> hicolor/scalable/apps/<APP_ID>.svg           full colour
#   symbolic-icon.svg -> hicolor/symbolic/apps/<APP_ID>-symbolic.svg  monochrome
#
# The colour icon keeps the source markup verbatim (groups, transforms and all)
# and only gets a clean root element, so nested `transform=` attributes survive.
# The symbolic icon has every fill stripped and repainted with `currentColor`.
#
# Only SVGs are produced. Rasterising to PNG would freeze the artwork at export
# time and reintroduce the drift the old PNG set suffered from; the tray
# rasterises the symbolic SVG at runtime instead (see src/tray.rs).
set -euo pipefail

cd "$(dirname "$0")/.."

APP_ID="com.chrisdaggas.datacleaner"

mkdir -p "data/icons/hicolor/scalable/apps" "data/icons/hicolor/symbolic/apps"

python3 - "$APP_ID" <<'PY'
import re
import sys

app_id = sys.argv[1]


def load(path):
    """Return (viewBox, inner markup) for an SVG, minus SVG Repo scaffolding."""
    svg = open(path, encoding="utf-8").read()
    svg = re.sub(r"<!DOCTYPE[^>]*>", "", svg)
    svg = re.sub(r"<\?xml[^>]*\?>", "", svg)

    root = re.search(r"<svg\b[^>]*>", svg)
    if not root:
        sys.exit(f"{path}: no <svg> element")
    view_box = re.search(r'viewBox="([^"]+)"', root.group(0))
    if not view_box:
        sys.exit(f"{path}: no viewBox; cannot place the artwork on a canvas")

    inner = svg[root.end():svg.rindex("</svg>")]
    # The exporter leaves two empty carrier groups behind; they only add noise.
    inner = re.sub(r'<g id="SVGRepo_(?:bg|tracer)Carrier"[^>]*/>', "", inner)
    return view_box.group(1), inner.strip()


def strip_fills(markup):
    """Drop every baked-in colour so `currentColor` can take over."""
    markup = re.sub(r'\sfill="(?!none)[^"]*"', "", markup)
    markup = re.sub(r"fill:\s*(?!none)[^;\"']+;?", "", markup)
    markup = re.sub(r'\sstyle="\s*"', "", markup)
    return markup


# --- full colour -----------------------------------------------------------
view_box, inner = load("logo.svg")
colour = f"""<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by scripts/export-app-icons.sh from logo.svg. Do not edit. -->
<svg
   xmlns="http://www.w3.org/2000/svg"
   width="128"
   height="128"
   viewBox="{view_box}"
   version="1.1">
  <title>Data Cleaner</title>
  {inner}
</svg>
"""

# --- symbolic --------------------------------------------------------------
# Fraction of the canvas the glyph fills. Tray panels leave no padding of their
# own, so the artwork is inset here instead: the viewBox is grown around its
# centre, which shrinks the drawing without touching any path data. GNOME's
# own symbolic icons span 14 of their 16 px, so the eraser (which fills 92.6%
# of symbolic-icon.svg) is scaled to match: 0.875 / 0.926.
SYMBOLIC_SCALE = 0.945

sym_view_box, sym_inner = load("symbolic-icon.svg")


def inset_view_box(view_box, scale):
    try:
        x, y, w, h = (float(n) for n in view_box.replace(",", " ").split())
    except ValueError:
        sys.exit(f"symbolic-icon.svg: cannot parse viewBox {view_box!r}")
    new_w, new_h = w / scale, h / scale
    return "{:g} {:g} {:g} {:g}".format(
        x - (new_w - w) / 2, y - (new_h - h) / 2, new_w, new_h
    )


sym_view_box = inset_view_box(sym_view_box, SYMBOLIC_SCALE)
sym_inner = strip_fills(sym_inner)
# Paint each shape explicitly: GTK's symbolic restyling targets the shape
# elements, not their ancestors.
sym_inner = re.sub(
    r"<(path|rect|circle|polygon|ellipse)\b",
    r'<\1 class="ColorScheme-Text" style="fill:currentColor"',
    sym_inner,
)
sym_inner = "\n".join("    " + line.strip() for line in sym_inner.splitlines() if line.strip())

# NOTE: `<svg` must stay near the top of the file. Image loaders sniff the
# format from the first few hundred bytes, and GNOME's glycin SVG loader
# rejects the file as "Unknown image format: application/xml" when a long
# comment header pushes the root element out of that window — which silently
# empties the tray's IconPixmap. Every explanatory comment therefore lives
# *inside* the root element, never above it.
symbolic = f"""<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns="http://www.w3.org/2000/svg"
   width="16"
   height="16"
   viewBox="{sym_view_box}"
   color="#ffffff"
   version="1.1">
  <!-- Generated by scripts/export-app-icons.sh from symbolic-icon.svg. Do not edit.

       Every shape paints with `currentColor` so the icon follows the surrounding
       foreground colour instead of carrying a baked-in fill:
         * GTK recolours symbolic icons by injecting a stylesheet that overrides
           `fill` on rect/circle/path with the widget's foreground colour.
         * KDE/Plasma StatusNotifier hosts swap the body of the
           `current-color-scheme` stylesheet below for the panel's text colour,
           which `.ColorScheme-Text` then feeds into `currentColor`.
         * Hosts that do neither still get a sensible result from the `color`
           attribute on the root element.
       The `color` default is only that last-resort fallback; src/tray.rs
       substitutes it per theme before rasterising the tray pixmap. -->
  <title>Data Cleaner</title>
  <style type="text/css" id="current-color-scheme">.ColorScheme-Text {{ color:#ffffff; }}</style>
  <g class="ColorScheme-Text" style="fill:currentColor;stroke:none">
{sym_inner}
  </g>
</svg>
"""

colour_path = f"data/icons/hicolor/scalable/apps/{app_id}.svg"
symbolic_path = f"data/icons/hicolor/symbolic/apps/{app_id}-symbolic.svg"
open(colour_path, "w", encoding="utf-8").write(colour)
open(symbolic_path, "w", encoding="utf-8").write(symbolic)
print(f"logo.svg          -> {colour_path}")
print(f"symbolic-icon.svg -> {symbolic_path}")
PY
